### ISSUE TITLE
Node 10 breaks stubmatic dynamic features

### ISSUE THREAD

**Issue by shani-cwt** [NaturalIntelligence/Stubmatic#12]
After switching node version from 8.9.4 to 10.13.0, dynamic features (evaluating keys at the response) is not working well. What I got in the response is just the evaluated key, not the entire response.

After debugging, I found the problem in lib/expressions/engine.js line 30 
`expressions[i]=new Expression(match[match.length-2], match[1]);`

The problem is that match.length is different with node.js 10 and node.js 8.
So for start index you get a string and not a number.
Please see attached screenshots.
![node8](https://user-images.githubusercontent.com/38466701/51611794-cc678500-1f28-11e9-83c3-40d760159bcb.jpg)
![node10](https://user-images.githubusercontent.com/38466701/51611796-cc678500-1f28-11e9-8e58-298eceb218a4.jpg)

**Comment by shani-cwt** [comment]
@amitguptagwl thanks I wouldnt have time for anytime soon, but perhaps later I will find the time for it

**Comment by amitguptagwl** [comment]
No problem. I'll arrange some time to fix it ASAP.
