### ISSUE TITLE
Error when calling from java web service client

### ISSUE THREAD

**Issue by ltabreu** [NaturalIntelligence/Stubmatic#8]
I have create a mock that work fine when its called from SoapUI, but fail when its called from a generated java web service client. I thing that the body is not recognizing propertly, because in the log, resolved is null.

**Comment by amitguptagwl** [comment]
What error are you getting? Run Stubmatic with debug options to check onscreen request console logs. There must be the problem with the input request only.

> Please [bookmark](https://github.com/NaturalIntelligence/Stubmatic/stargazers) this project.
